### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by spiritoosSanki** [Coreoz/Plume#5]
Salut,

J'ai créer le projet avec le jdk 9, il y a pas mal d'erreur.
Ajouter le support jdk9 serait cool !

++

**Comment by amanteaux** [comment]
Yes! Et même ajouter le support du jdk10 tant qu'à faire!

**Comment by spiritoosSanki** [comment]
Yes :D

**Comment by amanteaux** [comment]
Fixed in [Plume 2.0.0](https://github.com/Coreoz/Plume/releases/tag/2.0.0)!
